import {
  ForkKnife, Coffee, Pizza, Wine, Hamburger, IceCream,
  ShoppingCart, ShoppingBag, Gift, Tag, Storefront,
  Car, Bus, Train, Airplane, GasPump, Taxi, Bicycle,
  House, Lightbulb, Wrench, Couch,
  HeartStraight, FirstAid, Pill, Barbell,
  GameController, FilmStrip, MusicNote, Camera, Television,
  GraduationCap, Book, Briefcase, ChartLine,
  CurrencyDollar, Bank, PiggyBank, CreditCard, Wallet,
  Phone, WifiHigh, Devices,
  PawPrint, Tree, Flower, Confetti, Sparkle,
} from "@phosphor-icons/react";
import type { Icon } from "@phosphor-icons/react";

export const CATEGORY_ICONS: Record<string, Icon> = {
  forkknife: ForkKnife,
  coffee: Coffee,
  pizza: Pizza,
  wine: Wine,
  hamburger: Hamburger,
  icecream: IceCream,
  cart: ShoppingCart,
  bag: ShoppingBag,
  gift: Gift,
  tag: Tag,
  storefront: Storefront,
  car: Car,
  bus: Bus,
  train: Train,
  airplane: Airplane,
  gas: GasPump,
  taxi: Taxi,
  bicycle: Bicycle,
  house: House,
  bulb: Lightbulb,
  wrench: Wrench,
  couch: Couch,
  heart: HeartStraight,
  firstaid: FirstAid,
  pill: Pill,
  barbell: Barbell,
  game: GameController,
  film: FilmStrip,
  music: MusicNote,
  camera: Camera,
  tv: Television,
  graduation: GraduationCap,
  book: Book,
  briefcase: Briefcase,
  chart: ChartLine,
  dollar: CurrencyDollar,
  bank: Bank,
  piggy: PiggyBank,
  card: CreditCard,
  wallet: Wallet,
  phone: Phone,
  wifi: WifiHigh,
  devices: Devices,
  paw: PawPrint,
  tree: Tree,
  flower: Flower,
  confetti: Confetti,
  sparkle: Sparkle,
};

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICONS);

export const CATEGORY_COLORS = [
  "#ef4444", "#f97316", "#f59e0b", "#eab308",
  "#84cc16", "#22c55e", "#10b981", "#14b8a6",
  "#06b6d4", "#0ea5e9", "#3b82f6", "#4169e1",
  "#6366f1", "#8b5cf6", "#a855f7", "#d946ef",
  "#ec4899", "#f43f5e", "#9298a6", "#475569",
];
